### ISSUE TITLE
API behavior change for `torch_geometric.data`

### ISSUE THREAD

**Issue by JiaxuanYou** [vrtex-team/pytorch_geometric#101]
## 🐛 Bug

These are not necessarily bugs, but the API behavior has slightly changed.
1. `data.num_nodes` in stable PyG version sometimes returns a list of int, whereas in our fork only int is returned.
2. `dataset.slices` in stable PyG exists even when the dataset only has 1 graph; in our fork `dataset.slices` will be `None`.

## To Reproduce

1.  Regarding `data.num_nodes`
``` python
dataset = PygLinkPropPredDataset(name=name, root=dataset_dir)
print(dataset.data.num_nodes)
```
Terminal output:
``` bash
[235868]    # PyG stable
235868       # Our fork
```

2. Regarding `dataset.slices`
``` python
dataset = PygLinkPropPredDataset(name=name, root=dataset_dir)
print(dataset.data.slices)
```
Terminal output:
``` bash
{'x': tensor([     0, 235868]), 'edge_index': tensor([      0, 2358104]), 'edge_weight': tensor([      0, 2358104]), 'edge_year': tensor([      0, 2358104])}    # PyG stable
None       # Our fork
```

**Comment by rusty1s** [comment]
Thanks for reporting. The behaviour actually changed in PyG master, where we do not call `collate` anymore in case the dataset only exists of one graph. Do you think we need to fix it?

**Comment by JiaxuanYou** [comment]
I think the current one looks good. When a dataset has one/multiple graphs the returned values may have different formats, but it's not a big issue.
